name: Publish Image

on:
#   schedule:
#     - cron: '0 12 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Version Check
        id: versioncheck
        run: |
          
          VERSION=$(npm info meshcentral version)
          STABLE_VERSION=$(npm dist-tags meshcentral | grep stable | awk -F '[ ]' '{print $2}')
          
          echo "::set-output name=VERSION::$VERSION"
          echo "::set-output name=STABLE_VERSION::$STABLE_VERSION"
          
          #check if version has already been published
          docker manifest inspect ghcr.io/gurucomputing/meshcentral-docker:$VERSION > /dev/null
          echo "::set-output name=NOT_PREVIOUSLY_PUBLISHED::$?"

      - name: Output Version
        run: |
          echo "The selected version is ${{ steps.versioncheck.outputs.VERSION }}"
          echo "The latest stable version is ${{ steps.versioncheck.outputs.STABLE_VERSION }}"
          if [ "${{ steps.versioncheck.outputs.VERSION }}" = "${{ steps.versioncheck.outputs.STABLE_VERSION }}" ]
          then
            echo "the current version matches the stable version"
          else
            echo "the current version does not match the stable version"
          fi

      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and push Stable Docker Image
        uses: docker/build-push-action@v2
        if: ${{ steps.versioncheck.outputs.VERSION == steps.versioncheck.outputs.STABLE_VERSION && steps.versioncheck.outputs.NOT_PREVIOUSLY_PUBLISHED }}
        with:
          context: ./container-build
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:stable
            ghcr.io/${{ github.repository }}:${{ steps.versioncheck.outputs.VERSION }}
          push: true
          
      - name: Build and push Latest Docker Image
        uses: docker/build-push-action@v2
        if: ${{ steps.versioncheck.outputs.VERSION == steps.versioncheck.outputs.STABLE_VERSION && steps.versioncheck.outputs.NOT_PREVIOUSLY_PUBLISHED }}
        with:
          context: ./container-build
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.versioncheck.outputs.VERSION }}
          push: true
