name: Publish Image

on:
#   schedule:
#     - cron: '0 12 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Version Check
        id: versioncheck
        run: |
          echo "::set-output name=VERSION::$(npm info meshcentral version)"
          echo "::set-output name=STABLE_VERSION::$(npm dist-tags meshcentral | grep stable | awk -F '[ ]' '{print $2}')"
          # check if both versions are equal
          isStable() {
          [ "${{ steps.versioncheck.outputs.VERSION }}" = "${{ steps.versioncheck.outputs.STABLE_VERSION }}"
          }
          isStable
          echo "::set-output name=IS_STABLE::$?"

      - name: Output Version
        run: |
          echo "The selected version is ${{ steps.versioncheck.outputs.VERSION }}"
          echo "The latest stable version is ${{ steps.versioncheck.outputs.STABLE_VERSION }}"
          if ! ${{ steps.versioncheck.outputs.IS_STABLE }}; then
            echo "the current version does not match the stable version"
          fi

#       - name: Checkout Repository
#         uses: actions/checkout@V2
        
#       - name: Build and push Docker Image
#         uses: docker/build-push-action@v2
#         with:
#           context: ./container-build
#           push: true
