# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
#   schedule:
#     - cron: '0 12 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Version Check
        id: versioncheck
        uses: EndBug/version-check@v2.1.0
        with:
          file-url: https://raw.githubusercontent.com/Ylianst/MeshCentral/master/package.json
          
      # output version
      - name: Run a one-line script
        run: meshcentral version is ${{ steps.versioncheck.outputs.version }}
